### ISSUE TITLE
Check the semantics of max_power and min_speed in sendSpeedData

### ISSUE THREAD

**Issue by DarthBubi** [pilsbot/pilsbot_hw_ros#1]
The semantics of these parameters are not clear. A test drive concluded that `max_power = 100` is not enough to reach 1.5 m/s. Also, the `min_speed = 0` seems to have an interesting effect on the hardware controllers.

**Comment by Cirromulus** [comment]
The odometry of the HW-Controller is based on Halleffect over the coils. ~~This has a mediocre resolution in low speeds~~ (Edit: this version is not the poor mans zero-crossing back EMF, but actually precise on phase scale.)
May also/instead be caused by low resolution PWM on the H-Bridge.

**Comment by Cirromulus** [comment]
Power is an abstract PWM 1/Dutycycle ranging from 0 to 1000.
(actually 0-2^10, but HW-Controller strips the 24)
